In [3]:
import numpy as np

# Define the functions f(x, y) and g(x, y)
def f(x, y):
    return 3 * x**2 - y**2

def g(x, y):
    return 3 * x * y**2 - x**3 - 1

# Iteration scheme matrix
matrix = np.array([[1/6, 1/18],
                   [0, 1/6]])

# Define the iteration scheme
def iterate_nonlinear_system(x0, y0, iterations=10):
    results = [(x0, y0)]  # Store initial guess
    x, y = x0, y0
    for _ in range(iterations):
        # Compute f(x, y) and g(x, y)
        f_val = f(x, y)
        g_val = g(x, y)
        
        # Update (x, y) using the iteration scheme
        f_g_vector = np.array([f_val, g_val])
        delta_x_y = matrix @ f_g_vector
        x, y = x - delta_x_y[0], y - delta_x_y[1]
        
        # Store the results
        results.append((x, y))
        
    return results

# Starting point
x0, y0 = 1, 1

# Iterate for 10 steps
results_iteration = iterate_nonlinear_system(x0, y0, iterations=10)

# Return the results
import pandas as pd
iteration_df = pd.DataFrame(results_iteration, columns=['x', 'y'])
iteration_df

           x         y
0   1.000000  1.000000
1   0.611111  0.833333
2   0.537628  0.825846
3   0.509853  0.835075
4   0.499764  0.846058
5   0.497051  0.854660
6   0.497128  0.860259
7   0.497966  0.863453
8   0.498779  0.865071
9   0.499352  0.865789
10  0.499696  0.866053

In [4]:
# Define the Jacobian matrix of the system
def jacobian(x, y):
    j11 = 6 * x  # df/dx
    j12 = -2 * y  # df/dy
    j21 = 3 * y**2 - 3 * x**2  # dg/dx
    j22 = 6 * x * y  # dg/dy
    return np.array([[j11, j12], [j21, j22]])

# Newton's method iteration
def newtons_method(x0, y0, iterations=10):
    results = [(x0, y0)]  # Store initial guess
    x, y = x0, y0
    for _ in range(iterations):
        # Compute f(x, y) and g(x, y)
        f_val = f(x, y)
        g_val = g(x, y)
        
        # Compute Jacobian at the current (x, y)
        J = jacobian(x, y)
        
        # Solve the linear system J * delta = -[f(x, y), g(x, y)]
        F = np.array([f_val, g_val])
        delta = np.linalg.solve(J, -F)
        
        # Update (x, y)
        x, y = x + delta[0], y + delta[1]
        
        # Store the results
        results.append((x, y))
        
    return results

# Perform Newton's method for 10 iterations
results_newton = newtons_method(x0, y0, iterations=10)

# Display the results
newton_df = pd.DataFrame(results_newton, columns=['x', 'y'])
newton_df

           x         y
0   1.000000  1.000000
1   0.611111  0.833333
2   0.503659  0.852494
3   0.499964  0.866046
4   0.500000  0.866025
5   0.500000  0.866025
6   0.500000  0.866025
7   0.500000  0.866025
8   0.500000  0.866025
9   0.500000  0.866025
10  0.500000  0.866025

In [5]:
import numpy as np

# Define the ellipsoid equation and its partial derivatives
def f(x, y, z):
    return x**2 + 4*y**2 + 4*z**2 - 16

def f_x(x, y, z):
    return 2 * x

def f_y(x, y, z):
    return 8 * y

def f_z(x, y, z):
    return 8 * z

# Function to perform one iteration of the 3D scheme
def iterate_ellipsoid(x_n, y_n, z_n):
    fxn, fyn, fzn = f_x(x_n, y_n, z_n), f_y(x_n, y_n, z_n), f_z(x_n, y_n, z_n)
    denominator = fxn**2 + fyn**2 + fzn**2
    f_value = f(x_n, y_n, z_n)
    
    x_n1 = x_n - (f_value * fxn) / denominator
    y_n1 = y_n - (f_value * fyn) / denominator
    z_n1 = z_n - (f_value * fzn) / denominator
    
    return x_n1, y_n1, z_n1

# Initialize the starting point
x_n, y_n, z_n = 1.0, 1.0, 1.0

# Store results to show convergence
iterations = [(x_n, y_n, z_n)]

# Perform the iteration process for a number of steps
for _ in range(10):  # Let's try 10 iterations
    x_n, y_n, z_n = iterate_ellipsoid(x_n, y_n, z_n)
    iterations.append((x_n, y_n, z_n))

# Display results of the iterations
import pandas as pd

df_iterations = pd.DataFrame(iterations, columns=["x", "y", "z"])

df_iterations

           x         y         z
0   1.000000  1.000000  1.000000
1   1.106061  1.424242  1.424242
2   1.093926  1.361742  1.361742
3   1.093642  1.360329  1.360329
4   1.093642  1.360328  1.360328
5   1.093642  1.360328  1.360328
6   1.093642  1.360328  1.360328
7   1.093642  1.360328  1.360328
8   1.093642  1.360328  1.360328
9   1.093642  1.360328  1.360328
10  1.093642  1.360328  1.360328